# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cd2feed9dee0da3682105147694f76a20ee216f9c3c59aa7c4756c0d9247b4b207017b280c67d13a66fbfe56c848b67eb14691103d449ef7e7b8e405e177b49

test:
  secret_key_base: 1d4fa4de3283ca58f88b45a2ff65cb4e9a4fe7245a53e2d91b7ca017f60dcaa6352370680c72296beb74fd118afdba3c409612d230fba475138c82484fabe002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
